# Generated by Django 5.2.15 on 2026-06-23 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อรายการ')),
                ('source_filename', models.CharField(blank=True, max_length=300, verbose_name='ไฟล์วิดีโอ')),
                ('objects_detected', models.PositiveIntegerField(default=0, verbose_name='จำนวนวัตถุที่ตรวจพบ')),
                ('summary', models.TextField(blank=True, verbose_name='สรุปผล')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='บันทึกเมื่อ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
            ],
            options={
                'verbose_name': 'บันทึกผลวิเคราะห์',
                'verbose_name_plural': 'บันทึกผลวิเคราะห์',
                'ordering': ['-created_at'],
            },
        ),
    ]
